#!/bin/sh
# Writes static/js/config.js from environment variables. Use as the Cloudflare Pages
# build command (with NRC_API_BASE_URL set in the project's environment variables):
#
#   sh scripts/write-config.sh
#
# NRC_API_BASE_URL: base URL of the membership API, e.g. https://api.example.org
set -eu

: "${NRC_API_BASE_URL:?NRC_API_BASE_URL must be set, e.g. https://api.example.org}"
api_base_url="${NRC_API_BASE_URL%/}"

# Only plain http(s) origins with an optional path, so the value is safe to embed in JS.
if ! printf '%s' "$api_base_url" | grep -Eq '^https?://[A-Za-z0-9.-]+(:[0-9]+)?(/[A-Za-z0-9._~/-]*)?$'; then
    echo "NRC_API_BASE_URL is not a valid http(s) URL: $api_base_url" >&2
    exit 1
fi

config_path="$(dirname "$0")/../static/js/config.js"

cat > "$config_path" <<CONFIG
/**
 * Site configuration shared by pages that call backend services.
 * Generated by scripts/write-config.sh from NRC_API_BASE_URL; do not edit by hand.
 */
const NRC_CONFIG = Object.freeze({
    apiBaseUrl: "$api_base_url"
});
CONFIG

echo "Wrote $config_path (apiBaseUrl: $api_base_url)"
